// Validates the dictionary and generates build inputs:
//   apps/web/public/dictionary.json   (served at /dictionary.json)
//   apps/worker/src/keys.gen.ts       (public JWKs per env, for /.well-known/jwks.json)
import { createHash } from 'node:crypto';
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname } from 'node:path';
import { dictionaryFileSchema, jwkThumbprint, loadDictionary } from '@labkit/core';
import { ENVS, readPublicKeys, ROOT } from './lib';

/** Only touch files whose content changed: wrangler dev watches src/ and would rebuild forever. */
function writeIfChanged(path: string, content: string): void {
  if (existsSync(path) && readFileSync(path, 'utf8') === content) return;
  writeFileSync(path, content);
}

const raw = JSON.parse(readFileSync(`${ROOT}dictionary/dictionary.json`, 'utf8')) as unknown;
const parsed = dictionaryFileSchema.safeParse(raw);
if (!parsed.success) {
  console.error('dictionary/dictionary.json is invalid:', JSON.stringify(parsed.error.issues.slice(0, 5), null, 2));
  process.exit(1);
}
loadDictionary(parsed.data); // throws on duplicate LOINC

const frozen = JSON.parse(readFileSync(`${ROOT}dictionary/FROZEN.json`, 'utf8')) as { entries: Record<string, string> };
const byLoinc = new Map(parsed.data.entries.map((e) => [e.loinc, e]));
for (const [loinc, hash] of Object.entries(frozen.entries)) {
  const e = byLoinc.get(loinc);
  const actual = e && createHash('sha256').update(JSON.stringify({ loinc: e.loinc, display: e.display, text: e.text })).digest('hex');
  if (actual !== hash) {
    console.error(`FROZEN entry ${loinc} was removed or its loinc/display/text changed. Frozen labels can never change (SPEC §6.2).`);
    process.exit(1);
  }
}

mkdirSync(`${ROOT}apps/web/public`, { recursive: true });
writeIfChanged(`${ROOT}apps/web/public/dictionary.json`, JSON.stringify(parsed.data));

// Release builds (scripts/build-release.ts) set LABKIT_KEY_ENV so the Worker carries only its own
// environment's keys, never the throwaway dev key CI generates for the tests.
const onlyEnv = process.env.LABKIT_KEY_ENV;
const keysets: Record<string, unknown[]> = {};
for (const env of ENVS) {
  const keys = onlyEnv && env !== onlyEnv ? [] : readPublicKeys(env);
  for (const k of keys) {
    if ((await jwkThumbprint(k)) !== k.kid) throw new Error(`keys/${env}/${k.kid}.json: kid is not the RFC 7638 thumbprint`);
  }
  keysets[env] = keys;
}
writeIfChanged(
  `${ROOT}apps/worker/src/keys.gen.ts`,
  `// GENERATED by scripts/build-data.ts from keys/<env>/*.json. Do not edit.\nimport type { PublicJwk } from '@labkit/core';\n\nexport const KEYSETS: Record<string, PublicJwk[]> = ${JSON.stringify(keysets, null, 2)};\n`,
);
console.log(`build-data: ${parsed.data.entries.length} dictionary entries; keys ${ENVS.map((e) => `${e}=${keysets[e]!.length}`).join(' ')}`);

// Self-hosted pdf.js and OCR assets (CLAUDE.md: no CDNs). Served from /vendor/.
const req = createRequire(`${ROOT}packages/parsers/package.json`);
const pkgDir = (name: string, from = req) => dirname(from.resolve(`${name}/package.json`));
const pdfjs = pkgDir('pdfjs-dist');
const tess = pkgDir('tesseract.js');
const core = pkgDir('tesseract.js-core', createRequire(`${tess}/package.json`));
const eng = pkgDir('@tesseract.js-data/eng');
const VENDOR = `${ROOT}apps/web/public/vendor`;

function copyIfChanged(from: string, to: string): void {
  if (existsSync(to) && statSync(to).size === statSync(from).size) return;
  mkdirSync(dirname(to), { recursive: true });
  copyFileSync(from, to);
}
function copyDir(from: string, to: string, keep: (f: string) => boolean = () => true): void {
  for (const f of readdirSync(from)) if (keep(f) && statSync(`${from}/${f}`).isFile()) copyIfChanged(`${from}/${f}`, `${to}/${f}`);
}

// Legacy build: supports older iOS Safari versions.
copyIfChanged(`${pdfjs}/legacy/build/pdf.worker.min.mjs`, `${VENDOR}/pdfjs/pdf.worker.min.mjs`);
copyDir(`${pdfjs}/cmaps`, `${VENDOR}/pdfjs/cmaps`);
copyDir(`${pdfjs}/standard_fonts`, `${VENDOR}/pdfjs/standard_fonts`);
copyDir(`${pdfjs}/wasm`, `${VENDOR}/pdfjs/wasm`, (f) => /^(jbig2|openjpeg|qcms_bg)/.test(f));
copyIfChanged(`${tess}/dist/worker.min.js`, `${VENDOR}/ocr/worker.min.js`);
copyDir(core, `${VENDOR}/ocr/core`, (f) => /^tesseract-core(-simd|-relaxedsimd)?-lstm\.wasm\.js$/.test(f));
copyIfChanged(`${eng}/4.0.0_best_int/eng.traineddata.gz`, `${VENDOR}/ocr/lang/eng.traineddata.gz`);
console.log('build-data: vendor assets in apps/web/public/vendor/');
